package io.huskit.containers.api.cli;

public enum CommandType {

    // CONTAINERS
    CONTAINERS_LOGS,
    CONTAINERS_LOGS_FOLLOW,
    CONTAINERS_RUN,
    CONTAINERS_RUN_FOLLOW,
    CONTAINERS_REMOVE,
    CONTAINERS_LIST,
    CONTAINERS_INSPECT,

    // IMAGES
    IMAGES_LIST,
    IMAGES_REMOVE,
    IMAGES_INSPECT,
    IMAGES_PULL,

    // VOLUMES
    VOLUMES_INSPECT,
    VOLUMES_LIST,
    VOLUMES_REMOVE,
    VOLUMES_CREATE,
    VOLUMES_PRUNE,
}
