version: 2.1

executors:
  jdk-executor:
    docker:
      - image: cimg/openjdk:11.0.22

commands:
  prepare-gradle:
    steps:
      - run:
          name: Replace distributionUrl
          command: sed -i 's/-all.zip/-bin.zip/' gradle/wrapper/gradle-wrapper.properties


jobs:
  #       ------------------ UNIX ------------------
  gradle-build-unix:
    executor: jdk-executor
    steps:
      - checkout
      - prepare-gradle
      - restore_cache:
          keys:
            - gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
      - run:
          name: "gradle assemble unix"
          command: "./gradlew assemble --no-configuration-cache --no-build-cache --no-configure-on-demand --stacktrace"
      - save_cache:
          paths:
            - ~/.gradle/wrapper/
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches/
          key: gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}

  gradle-build-test-unix:
    executor: jdk-executor
    steps:
      - checkout
      - prepare-gradle
      - restore_cache:
          keys:
            - gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
      - run:
          name: "Testing of the internal-convention-plugin"
          command: "./gradlew :internal-convention-plugin:test --no-configuration-cache --no-build-cache --no-configure-on-demand --stacktrace"
      - run:
          name: "Save test results unix"
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results

  gradle-unit-test-unix:
    executor: jdk-executor
    steps:
      - checkout
      - run:
          name: Print branch
          command: echo << pipeline.git.branch >>
      - prepare-gradle
      - restore_cache:
          keys:
            - gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
      - run:
          name: "Run unit tests in unix"
          command: "./gradlew test --no-configuration-cache --no-build-cache --no-configure-on-demand --stacktrace"
      - run:
          name: "Save test results unix"
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results

  gradle-integration-test-unix:
    executor: jdk-executor
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
      - run:
          name: "Run integration tests in unix"
          command: "./gradlew integrationTest --no-configuration-cache --no-build-cache --no-configure-on-demand --stacktrace"
      - run:
          name: "Save test results unix"
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results

  gradle-functional-test-unix:
    executor: jdk-executor
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
      - run:
          name: "Run functional tests in unix"
          command: "./gradlew functionalTest --no-configuration-cache --no-build-cache --no-configure-on-demand --stacktrace"
      - run:
          name: "Save test results unix"
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results

workflows:
  Verify:
    when:
      or:
        - equal: [ "dev", "dev" ]
    jobs:
      - gradle-build-unix
      - gradle-unit-test-unix
      - gradle-integration-test-unix
      - gradle-functional-test-unix
