version: 2.1

jobs:
  #       ------------------ UNIX ------------------
  gradle-build-unix:
    docker:
      - image: cimg/openjdk:11.0.22
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
      - run:
          name: "gradle assemble unix"
          command: "./gradlew assemble --no-configuration-cache --no-build-cache --no-configure-on-demand --stacktrace"
      - save_cache:
          paths:
            - ~/.gradle/wrapper/
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches/
          key: gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
  gradle-build-test-unix:
    docker:
      - image: cimg/openjdk:11.0.22
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
      - run:
          name: "Testing of the internal-convention-plugin"
          command: "./gradlew :internal-convention-plugin:test --no-configuration-cache --no-build-cache --no-configure-on-demand --stacktrace"
      - run:
          name: "Save test results unix"
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
  gradle-unit-test-unix:
    docker:
      - image: cimg/openjdk:11.0.22
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
      - run:
          name: "Run unit tests in unix"
          command: "./gradlew test --no-configuration-cache --no-build-cache --no-configure-on-demand --stacktrace"
      - run:
          name: "Save test results unix"
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
  gradle-integration-test-unix:
    docker:
      - image: cimg/openjdk:11.0.22
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - restore_cache:
          keys:
            - gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
      - run:
          name: "Run integration tests in unix"
          command: "./gradlew integrationTest --no-configuration-cache --no-build-cache --no-configure-on-demand --stacktrace"
      - run:
          name: "Save test results unix"
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
  gradle-functional-test-unix:
    docker:
      - image: cimg/openjdk:11.0.22
    steps:
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - checkout
      - restore_cache:
          keys:
            - gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
      - run:
          name: "Run functional tests in unix"
          command: "./gradlew functionalTest --no-configuration-cache --no-build-cache --no-configure-on-demand --stacktrace"
      - run:
          name: "Save test results unix"
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results


  #       ------------------ MAC ------------------
  gradle-build-mac:
    macos:
      xcode: "14.2.0"
    steps:
      - checkout
      - run:
          name: "gradle assemble mac"
          command: "./gradlew assemble --no-configuration-cache --no-build-cache --no-configure-on-demand --stacktrace"

  gradle-test-mac:
    macos:
      xcode: "14.2.0"
    steps:
      - checkout
      - run:
          name: "Run unit tests in mac"
          command: "./gradlew test --no-configuration-cache --no-build-cache --no-configure-on-demand --stacktrace"
      - run:
          name: "Save test results mac"
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results

  gradle-integration-test-mac:
    macos:
      xcode: "14.2.0"
    steps:
      - checkout
      - run:
          name: "Run integration tests in mac"
          command: "./gradlew integrationTest --no-configuration-cache --no-build-cache --no-configure-on-demand --stacktrace"
      - run:
          name: "Save test results mac"
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results

  gradle-functional-test-mac:
    macos:
      xcode: "14.2.0"
    steps:
      - checkout
      - run:
          name: "Run functional tests in mac"
          command: "./gradlew functionalTest --no-configuration-cache --no-build-cache --no-configure-on-demand --stacktrace"
      - run:
          name: "Save test results mac"
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results


workflows:
  gradle-build-unix:
    jobs:
      - gradle-build-unix
  gradle-test-unix-fast:
    jobs:
      - gradle-unit-test-unix
      - gradle-integration-test-unix
  gradle-test-unix-slow:
    jobs:
      - gradle-functional-test-unix
  gradle-build-mac:
    jobs:
      - hold:
          type: approval
      - gradle-build-mac:
          requires:
            - hold
      - gradle-test-mac:
          requires:
            - hold
      - gradle-integration-test-mac:
          requires:
            - hold
      - gradle-functional-test-mac:
          requires:
            - hold
