name: Verify

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2019, macos-11.0 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/setup-gradle